# Generated by Django 4.2.8 on 2023-12-05 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nama_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=255)),
                ('harga', models.CharField(max_length=15)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_service.kategori')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_service.status')),
            ],
        ),
    ]
